### ISSUE TITLE
[BUG] My CSS is too powerful for the current syntax highlighter

### ISSUE THREAD

**Issue by madprops** [DonJayamanne/gitHistoryVSCode#749]
v1.81.1

![css2345](https://github.com/DonJayamanne/gitHistoryVSCode/assets/206498/2daf2a19-7811-4f4a-981e-8d1b40f69c29)

**Comment by madprops** [comment]
```css
.item > div:nth-child(1 of :not(.hidden))  {
  padding-left: var(--item_margin);
}

.item > div:nth-last-child(1 of :not(.hidden)) {
  padding-right: var(--item_margin);
}
```
